sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 7
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
